### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by DanielRuf** [Rowno/sitemap-urls#3]
The last release was in 2015. It would be great to have a new working release.

**Comment by Rowno** [comment]
Is there anything that isn't working? The only things that have changed since then have been upgrading the dependencies and a test suite rewrite.

**Comment by DanielRuf** [comment]
We need a new release with the updated dependencies due to the security and our Node.js environment versions.

Even doing these things should increase the minor version according to SemVer.

**Comment by Rowno** [comment]
💥  https://github.com/Rowno/sitemap-urls/releases/tag/v3.0.0

**Comment by DanielRuf** [comment]
Awesome, thanks.
